# Default values for steedos-community.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: steedos/steedos-community
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.2"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
storageClass: ""

services:
  steedos:
    config:
      root_url: "https://csc.dev.steedos.cn"
      cacher: "redis://redis:6379"
      transporter: "redis://redis:6379/2"
      mongo_url: "mongodb://mongodb:27017/steedos"
      mongo_oplog_url: "mongodb://mongodb:27017/local"
      enable_password_login: "yes"
      cfs:
        store: "local"
        local:
          folder: "/app/storage"
        aws:
          endpoint: ""
          bucket: ""
          accessKeyId: ""
          secretAccessKey: ""
          s3ForcePathStyle: "true"
          signatureVersion: "v4"
          region: ""
    data_storage: "1Gi"

  redis:
    image: "ecr.aws.steedos.cn/dockerhub/bitnami/redis:6.2"
  
  mongodb:
    env:
      allow_empty_password: "yes"
      mongodb_enable_journal: "true"
      mongodb_advertised_hostname: "mongodb"
      mongodb_initial_primary_host: "mongodb"
      mongodb_replica_set_mode: "primary"
      mongodb_replica_set_name: "steedos"
    image: "ecr.aws.steedos.cn/dockerhub/bitnami/mongodb:4.4"
    storage: "2Gi"
    data_path: "/bitnami"


serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "default"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: steedos-tls-secret
      hosts:
        - chart-example.local
    

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

# tolerations: []
tolerations:
  - key: "node.kubernetes.io/unschedulable"
    operator: "Equal"
    value: ""
    effect: "NoSchedule"

affinity: {}
