apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "steedos-community.fullname" . }}
  labels:
    {{- include "steedos-community.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "steedos-community.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "steedos-community.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "steedos-community.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-myservice
          image: curlimages/curl:7.68.0
          command: ['sh', '-c', 'until curl mongodb:27017; do echo waiting for mongodb; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ROOT_URL
              value: {{ .Values.services.steedos.config.root_url }}
            - name: STEEDOS_CFS_STORE
              value: {{ .Values.services.steedos.config.store }}
            - name: STEEDOS_STORAGE_DIR
              value:  {{ .Values.services.steedos.config.folder }}
            - name: CACHER
              value: {{ .Values.services.steedos.config.cacher }}
            - name: MONGO_URL
              value: {{ .Values.services.steedos.config.mongo_url }}
            - name: MONGO_OPLOG_URL
              value: {{ .Values.services.steedos.config.mongo_oplog_url }}
            - name: TRANSPORTER
              value: {{ .Values.services.steedos.config.transporter }}
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:3000/api/health
            failureThreshold: 3
            periodSeconds: 60
            timeoutSeconds: 10
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/.steedos
              name: steedos-installed-packages
            - mountPath: /app/storage
              name: steedos-data
          args:
            - yarn
            - start
      restartPolicy: Always
      volumes:
        - name: steedos-installed-packages
          persistentVolumeClaim:
            claimName: steedos-installed-packages
        - name: steedos-data
          persistentVolumeClaim:
            claimName: steedos-data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
