apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      tolerations:
      - key: "node.kubernetes.io/unschedulable"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      containers:
        - args:
            - redis-server
            - --save
            - ""
            - --appendonly
            - "no"
            - --loglevel
            - warning
          image: {{ .Values.services.redis.image }}
          name: redis
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
