apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: steedos-data
  name: steedos-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.services.steedos.data_storage }}
  storageClassName: {{ .Values.services.steedos.storageClass }}
status: {}
